<?php

/**
 * @file
 * Contains idix_rgpd.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function idix_rgpd_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the idix_rgpd module.
    case 'help.page.idix_rgpd':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Manage RGPD parameters') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function idix_rgpd_theme($existing, $type, $theme, $path) {
  return array(
    'idix_rgpd_script_pre_init' => array(
      'template' => 'templates/idix-rgpd-script-pre-init'
    ),
    'idix_rgpd_script_init' => array(
      'template' => 'templates/idix-rgpd-script-init'
    ),
    'idix_rgpd_youtube' => array(
      'variables' => array(
        'video_id' => NULL,
        'width' => NULL,
        'height' => NULL,
        'autoplay' => FALSE
      ),
      'template' => 'templates/idix-rgpd-youtube'
    ),
    'idix_rgpd_script_gajs' => array(
      'variables' => array(
        'ua_id' => NULL,
        'custom_script' => NULL
      ),
      'template' => 'templates/idix-rgpd-script-gajs'
    ),
    'idix_rgpd_script_analytics' => array(
      'variables' => array(
        'ua_id' => NULL,
        'custom_script' => NULL
      ),
      'template' => 'templates/idix-rgpd-script-analytics'
    ),
    'idix_rgpd_script_youtube' => array(
      'template' => 'templates/idix-rgpd-script-youtube'
    )
  );
}

/**
 * Implements hook_preprocess_html().
 */
// function idix_rgpd_preprocess_html(&$variables) {
//   if (\Drupal::service('theme.manager')->getActiveTheme()->getName() == \Drupal::config('system.theme')->get('default')) {
//     drupal_add_js(theme('idix_rgpd_script_pre_init'), array('type' => 'inline'));
//     drupal_add_js(drupal_get_path('module', 'idix_rgpd') . '/tarteaucitron/tarteaucitron.js');
//     drupal_add_js(_idix_rgpd_build_script(), 'inline');
//     $variables['classes_array'][] = 'rgpd-consent';
//   }
// }

/**
 * Implements hook_preprocess_HOOK().
 */
// function idix_rgpd_preprocess_idix_rgpd_script_init(&$variables) {
//   $variables['options'] = _idix_rgpd_get_init_options();
// }

// function _idix_rgpd_build_script () {
//   $script = theme('idix_rgpd_script_init');

//   if (variable_get('rgpd_gajs_enabled')) {
//     $script .= theme('idix_rgpd_script_gajs', [
//       'ua_id' => variable_get('rgpd_gajs_id'),
//       'custom_script' => variable_get('rgpd_gajs_script')
//     ]);
//   }

//   if (variable_get('rgpd_analytics_enabled')) {
//     $script .= theme('idix_rgpd_script_analytics', [
//       'ua_id' => variable_get('rgpd_analytics_id'),
//       'custom_script' => variable_get('rgpd_analytics_script')
//     ]);
//   }

//   if (variable_get('rgpd_youtube_enabled')) {
//     $script .= theme('idix_rgpd_script_youtube');
//   }

//   return $script;
// }

// function _idix_rgpd_get_init_options () {
//   $store_key = 'rgpd_conf_';
//   $options = _idix_rgpd_get_default_options();
//   foreach ($options as $key => &$value) {
//     if ($stored_value = variable_get($store_key . $key, $value)) {
//       $value = gettype($value) === 'boolean' ? (bool) $stored_value : $stored_value;
//     }
//   }

//   $options = array_filter($options, function ($value) {
//     return $value !== NULL;
//   });

//   return $options;
// }

// function _idix_rgpd_get_default_options () {
//   return [
//     'hashtag' => '#rgpdconsent', /* Ouverture automatique du panel avec le hashtag */
//     'cookieName' => 'rgpdconsent',
//     'highPrivacy' => FALSE, /* désactiver le consentement implicite (en naviguant) ? */
//     'orientation' => 'bottom', /* le bandeau doit être en haut (top) ou en bas (bottom) ? */
//     'adblocker' => FALSE, /* Afficher un message si un adblocker est détecté */
//     'showAlertSmall' => FALSE, /* afficher le petit bandeau en bas à droite ? */
//     'cookieslist' => FALSE, /* Afficher la liste des cookies installés ? */
//     'removeCredit' => TRUE, /* supprimer le lien vers la source ? */
//     'handleBrowserDNTRequest' => FALSE, /* Deny everything if DNT is on */
//     'cookieDomain' => NULL, /* Nom de domaine sur lequel sera posé le cookie pour les sous-domaines */
//     'AcceptAllCta' => TRUE, /* Show the accept all button when highPrivacy on */
//     'moreInfoLink' => FALSE, /* Show more info link */
//     'privacyUrl' => '', /* Privacy policy url */
//     'useExternalCss' => FALSE, /* If false, the tarteaucitron.css file will be loaded */
//     'readmoreLink' => "/cookiespolicy" /* Change the default readmore link pointing to opt-out.ferank.eu */
//   ];
// }

// function _idix_rgpd_get_services ($service = NULL, $type = NULL) {
//   $services = [
//     "gajs" => [
//       "type" => "analytic",
//       "name" => "Google Analytics (ga.js)",
//     ],
//     "analytics" => [
//       "type" => "analytic",
//       "name" => "Google Analytics (universal)",
//     ],
//     "youtube" => [
//       "type" => "video",
//       "name" => "YouTube",
//       "regexp" => [
//         "/youtube\.com\/embed\/([a-z0-9\-_]+)/i"
//       ]
//     ]
//   ];

//   // filtering options
//   if ($service != NULL) {
//     return isset($services[$service]) ? $services[$service] : NULL;
//   }
//   elseif ($type != NULL) {
//     if (gettype($type) == 'string') {
//       $type = [$type];
//     }
//     return array_filter($services, function ($service) use ($type) {
//       return in_array($service['type'], $type);
//     });
//   }

//   return $services;
// }
